# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [4]:
x=np.arange(10,49)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [7]:
arr=x.shape
arr

(39,)

5. Print the type of the previous array in question 3

In [8]:
print(type(x))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [10]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

7. Print the dimension of the array in question 3


In [13]:
print(len(x))

39


8. Create a boolean array with all the True values

In [15]:
y=np.ones((3,3), dtype=bool)
y

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

9. Create a two dimensional array




In [16]:
array=np.arange(15).reshape(3,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

10. Create a three dimensional array



In [17]:
array=np.arange(64).reshape(4,4,4)
array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [18]:
reverse=x[::-1]
reverse

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [22]:
x=np.zeros(10)
print(x)
print("update 6th value to 11:")
x[5]=1
x

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
update 6th value to 11:


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [23]:
z=np.identity(3)
print("3*3 matrix:")
z

3*3 matrix:


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [24]:
arr=np.array([1,2,3,4,5])
print("int array:", arr)
arr=arr.astype("float64")
print("float array:", arr)

int array: [1 2 3 4 5]
float array: [1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [25]:
arr1=np.array([[1.,2.,3.],[4.,5.,6.]])
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
mul=np.multiply(arr1, arr2)
mul

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [26]:
arr1=np.array([[1.,2.,3.],[4.,5.,6.]])
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
com=arr1==arr2
result=com.all()
result

False

17. Extract all odd numbers from arr with values(0-9)

In [27]:
o=np.array([0,1,2,3,4,5,6,7,8,9,])
x=o[o % 2 == 1]
x

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [30]:
o=np.array([0,1,2,3,4,5,6,7,8,9])
o[o % 2 == 1] = -1
o

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [31]:
arr = np.arange(13)
print("previous array:", arr)
arr[5]=12
arr[6]=12
arr[7]=12
arr[8]=12
print("latest array:", arr)

previous array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12]
latest array: [ 0  1  2  3  4 12 12 12 12  9 10 11 12]


20. Create a 2d array with 1 on the border and 0 inside

In [32]:
x=np.ones((4,4))
print("current array:", arr)
print(x)
print("1 on the border and 0 inside")
x[1:-1, 1:-1] = 0
x

current array: [ 0  1  2  3  4 12 12 12 12  9 10 11 12]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
1 on the border and 0 inside


array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [34]:
arr2d=np.array([[1,2,30],[4,5,6],[7,8,9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2, 30],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [38]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d[0,:]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [39]:
arr1=np.arange(0,9).reshape(3,3)
print(arr1)
arr=arr1[:1, 1:3]
arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 2]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [42]:
arr1=np.arange(0,9).reshape(3,3)
print(arr1)
arr=arr1[1:2,1:2]
arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[4]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [43]:
arr1=np.arange(0,9).reshape(3,3)
print(arr1)
arr=arr1[:2,2:3]
arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [44]:
x=np.random.random((10,10))
print("current array:")
print(x)
xmin, xmax=x.min(),x.max()
print("Minimum Value:", xmin)
print("Maximum Value:", xmax)

current array:
[[0.578976   0.07545156 0.13698319 0.01081438 0.55084199 0.26063723
  0.43108972 0.43289366 0.38748906 0.70514333]
 [0.09004107 0.27009908 0.47145046 0.76202562 0.07227028 0.81554769
  0.52495727 0.88272579 0.18710726 0.54049823]
 [0.22175145 0.57549665 0.18850456 0.55327372 0.58741084 0.36387891
  0.01967257 0.29339896 0.09043956 0.27740721]
 [0.98535031 0.85664557 0.77165349 0.21339133 0.20340716 0.94620757
  0.86651692 0.40603164 0.36120102 0.69784334]
 [0.42749547 0.31787791 0.7721736  0.36366701 0.41791473 0.00233153
  0.27221871 0.44128128 0.71313392 0.45680684]
 [0.69401428 0.62968438 0.81876746 0.09697235 0.80210422 0.69438944
  0.35456419 0.07204069 0.33418954 0.7313685 ]
 [0.52845251 0.42905167 0.47669174 0.11727279 0.73995373 0.16561547
  0.33409294 0.41961235 0.60227449 0.25191408]
 [0.54354559 0.66085581 0.61526985 0.6386848  0.26183529 0.5656959
  0.30282167 0.52759802 0.19054987 0.42765992]
 [0.30061493 0.30035935 0.98028591 0.85677037 0.72958611 0.1666276

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [49]:
a=np.array([1,2,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [50]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(np.intersect1d(a,b)))

(array([0, 1], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [54]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
x=data[names != 'Will']
x

array([[ 1.46750856,  0.07367329, -1.85271019,  0.49447159],
       [ 1.96285697,  0.16755456, -2.01507419, -1.17722947],
       [-0.33729831,  0.85366042,  1.17370147, -0.26290302],
       [-0.25464241,  0.02542754,  1.00008906, -0.98202876],
       [ 0.34821874,  1.086937  , -1.02896416,  0.24373532]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [56]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
x=data[names != 'Will']
y=data[names != "Joe"]
print(x,y)

[[ 1.39990807 -0.09282708 -0.81565025  0.67118866]
 [ 1.61318611  0.33456601 -0.88253495  0.39845622]
 [ 1.49296844 -0.43792232  0.38151875 -1.3814406 ]
 [-1.72135965 -0.40300377 -0.80211153  0.09338158]
 [ 0.35258971 -0.78273076 -0.18697652 -0.97363743]] [[ 1.39990807 -0.09282708 -0.81565025  0.67118866]
 [-1.45092217 -0.25241586  0.35770715 -1.01981988]
 [ 1.49296844 -0.43792232  0.38151875 -1.3814406 ]
 [-0.05685701 -1.24535649  0.79250091 -1.36302447]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [57]:
array=np.random.randn(1,15).reshape(5,3)
array

array([[ 1.57721319,  2.66800435, -0.3694831 ],
       [ 0.03496039,  0.51488592, -1.35280386],
       [-1.2035966 ,  1.41971909,  0.31426937],
       [-0.44717269,  0.67226394,  0.27727359],
       [-0.6292411 , -0.67321686, -1.13552676]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [58]:
array=np.random.randn(1,16).reshape(2,2,4)
array

array([[[ 0.82089657,  0.82989266, -0.38824898, -1.11996133],
        [-0.92362192, -0.38670923,  0.4179618 , -1.06217404]],

       [[ 0.63890055,  0.83098059,  0.74641502,  1.37759031],
        [ 0.85134392, -0.12467953,  0.25220111,  0.77300426]]])

33. Swap axes of the array you created in Question 32

In [59]:
array=np.random.randn(1,16).reshape(2,4,2)
array

array([[[-0.74320724, -0.59463884],
        [-0.19076546, -0.69707544],
        [ 0.00569507,  1.39494655],
        [ 0.91510353, -0.07313351]],

       [[-0.90748143, -1.9514549 ],
        [-1.41647088,  0.20655311],
        [ 1.93061153,  0.99691505],
        [-1.12337634, -4.2253857 ]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [60]:
array=np.arange(10)
array=np.sqrt(array)
x=np.where(array<0.5,0,array)
x

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [61]:
arr1=np.random.random(12)
arr2=np.random.random(12)
arr3=np.max((arr1,arr2))
arr3

0.9448918636983631

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [63]:
names=np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
_,idx = np.unique(names, return_index=True)
(names[np.sort(idx)])

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [64]:
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
result=np.setdiff1d(a,b)
result

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [67]:
sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray=np.delete(sampleArray, 1, axis=1)
print(sampleArray)
newColumn=np.array([10,10,10])
sampleArray=np.insert(sampleArray, 1, newColumn, axis=1)
print(sampleArray)

[[34 73]
 [82 12]
 [53 66]]
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [75]:
x=np.array([[1.,2.,3.],[4.,5.,6]])
y=np.array([[6.,23.],[-1.,7.],[8.,9.]])
z=np.dot(x,y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [77]:
array=np.random.random(20)
Sum=np.cumsum(array)
Sum

array([0.43075232, 0.51252424, 1.05962103, 2.03317501, 2.10338854,
       2.78070411, 3.01060014, 3.3038565 , 4.03513985, 4.16928992,
       4.29534453, 4.8565529 , 5.73351896, 5.819108  , 5.98951812,
       6.85036162, 7.3726568 , 7.99128374, 8.3608474 , 8.98405139])