# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr2d=np.reshape(arr,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
## Question:2

###  How to stack two arrays vertically?

In [ ]:
#### Desired Output::

In [3]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.vstack((a,b))
c

array([[1, 2, 3],
       [4, 5, 6]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [4]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [5]:
arr1=np.array([[1,2,3],[2,4,5],[1,2,3]])
print("initial array", str(arr1))
result=arr1.flatten()
print("New resulting array:", result)

initial array [[1 2 3]
 [2 4 5]
 [1 2 3]]
New resulting array: [1 2 3 2 4 5 1 2 3]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [13]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
z = x.flatten()
print(z)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [11]:
x= np.random.random((5,5))
y = np.square(x)
print(y)

[[3.01991559e-01 8.72843385e-01 2.69094003e-03 9.18662382e-02
  7.91011849e-01]
 [2.36013224e-01 2.63626773e-02 2.30893383e-01 5.53686633e-01
  4.28816837e-02]
 [6.75842540e-02 4.80045988e-01 2.34947141e-01 8.65924047e-01
  4.18447289e-01]
 [5.33058844e-01 8.31894441e-01 6.36957225e-01 9.04227455e-01
  8.17454558e-01]
 [6.89952409e-02 2.73886134e-02 1.03052116e-01 8.61575908e-01
  6.24254423e-05]]


## Question:8

### Create 5x6 an array and find the mean?

In [16]:
y = np.random.random((5,6))
print(y)
z = np.mean(y)
print("Mean of the Y: " ,z)

[[0.91833989 0.4005679  0.23519234 0.32504894 0.5382088  0.29898217]
 [0.88722184 0.9736146  0.05102234 0.7099074  0.33417324 0.38021091]
 [0.98392128 0.70717878 0.38088473 0.65536333 0.40856313 0.61511874]
 [0.21521245 0.22730767 0.70002978 0.71610418 0.2132954  0.29463648]
 [0.53092506 0.4859057  0.26323358 0.94633927 0.45763586 0.63316248]]
Mean of the Y:  0.5162436090960948


## Question:9

### Find the standard deviation of the previous array in Q8?

In [17]:
x = np.random.random((5,6))
y = np.std(x, dtype = np.float32)
print("Deviation of array:" , y)

Deviation of array: 0.27531624


## Question:10

### Find the median of the previous array in Q8?

In [18]:
y = np.random.random((5,6))
z = np.median(y)
print("Median of array:", z)

Median of array: 0.5382988298538478


## Question:11

### Find the transpose of the previous array in Q8?

In [20]:
x = np.array([[0,1,2],[3,4,5]])
y = np.transpose(x)
print(y)

[[0 3]
 [1 4]
 [2 5]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [22]:
narray=np.array([[36,15,95,21],[10,14,12,5],[1,34,71,21],[51,21,40,25]])
print("4*4 array:")
print(narray)

Sum=np.trace(narray)
print("Sum of the array:", Sum)


4*4 array:
[[36 15 95 21]
 [10 14 12  5]
 [ 1 34 71 21]
 [51 21 40 25]]
Sum of the array: 146


## Question:13

### Find the determinant of the previous array in Q12?

In [23]:
narray=np.array([[36,15,95,21],[10,14,12,5],[1,34,71,21],[51,21,40,25]])
determinant=np.linalg.det(narray)
print("Determinant of the array:", determinant)

Determinant of the array: 583444.0000000002


## Question:14

### Find the 5th and 95th percentile of an array?

In [24]:
narray=np.array([[36,15,95,21],[10,14,12,5],[1,34,71,21],[51,21,40,25]])
percentile_5th = np.percentile(narray, 5)
print("5th percentile of array:", percentile_5th)
percentile_95th = np.percentile(narray, 95)
print("95th percentile of array:", percentile_95th)

5th percentile of array: 4.0
95th percentile of array: 77.0


## Question:15