# Reading Recipes 

Note: Data file is recipes.csv Attached with jupyter notebook

In [1]:
#type your code here
import numpy as np

2. All of Alize’s recipes call for milk, eggs, sugar, flour, and butter. For example, her cupcake recipe calls for:

Flour Sugar Eggs Milk Butter 2 cups 0.75 cups 2 eggs 1 cups 0.5 cups Create a NumPy array that represents this data. Each element should be a number (i.e., 2 for “2 cups”). Save this array as cupcakes.

In [4]:
#type your code here
cupcakes = np.array([2, 0.75, 2, 1, 0.5])
print("Cupcakes")
print(cupcakes)

Cupcakes
[2.   0.75 2.   1.   0.5 ]


3. Alize’s assistant has compiled all of her recipes into a csv (comma-separated variable) file called recipes.csv. Load this file into a variable called recipes.

###########Explore yourselves how to load a csv file in numpy#######

In [9]:
#type your code here
recipes=np.genfromtxt('recipes.csv', delimiter=',')
print('Recipes')
recipes


Recipes


array([[2.   , 0.75 , 2.   , 1.   , 0.5  ],
       [1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ],
       [4.   , 0.5  , 2.   , 2.   , 0.5  ]])

4.Display recipes using print.
Display recipes using print.


Each row represents a different recipe. Each column represents a different ingredient.

Recipe	       Cups of Flour	Cups of Sugar	Eggs	Cups of Milk	Cups of Butter

Cupcakes	         …	              …	          …	         …	              …

Pancake	             …                …	          …	         …	              …

Cookie	             …	              …	          …	         …	              …

Bread	             …	              …	          …	         …	              …

In [26]:
#type your code here
print('\tFlour(Cups) \t Sugar(Cups) \t Eggs(QTY) \t Milk(Cups) \t Butter(Cups)')
print(f'Cupcake\t {recipes[0,0]} \t\t {recipes[0,1]} \t\t {recipes[0,2]} \t\t {recipes[0,3]} \t\t {recipes[0,4]}')
print(f'Pancake\t {recipes[1,0]} \t\t {recipes[1,1]} \t\t {recipes[1,2]} \t\t {recipes[1,3]} \t\t {recipes[1,4]}')
print(f'Cookie\t {recipes[2,0]} \t\t {recipes[2,1]} \t\t {recipes[2,2]} \t\t {recipes[2, 3]} \t\t {recipes[2, 4]}')
print(f'Bread\t {recipes[3,0]} \t\t {recipes[3,1]} \t\t {recipes[3,2]} \t\t {recipes[3,3]} \t\t {recipes[3,4]}')

	Flour(Cups) 	 Sugar(Cups) 	 Eggs(QTY) 	 Milk(Cups) 	 Butter(Cups)
Cupcake	 2.0 		 0.75 		 2.0 		 1.0 		 0.5
Pancake	 1.0 		 0.125 		 1.0 		 1.0 		 0.125
Cookie	 2.75 		 1.5 		 1.0 		 0.0 		 1.0
Bread	 4.0 		 0.5 		 2.0 		 2.0 		 0.5


5.The 3rd column represents the number of eggs that each recipe needs.

Select all elements from the 3rd column and save them to the variable eggs.

In [27]:
#type your code here
Eggs = recipes[:,2]
print(f'Eggs : \n{Eggs}')

Eggs : 
[2. 1. 1. 2.]


6.Which recipes require exactly 1 egg? Use a logical statement to get True or False for each value of eggs.

In [31]:
#type your code here
recipes[Eggs == 1]

array([[1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ]])

7.Alize is going to make 2 batches of cupcakes (1st row) and 1 batch of cookies (3rd row).

You already have a variable for cupcakes. Create a variable for cookies with the data from the 3rd row.


In [34]:
#type your code here
Cookies = recipes[2,:]
print("Cookies")
Cookies

Cookies


array([2.75, 1.5 , 1.  , 0.  , 1.  ])

8.
Get the number of ingredients for a double batch of cupcakes by using multiplication on cupcakes. Save your new variable to double_batch.

In [36]:
#type your code here
double_batch = cupcakes * 2
print("Double_batch")
double_batch

Double_batch


array([4. , 1.5, 4. , 2. , 1. ])

9.
Create a new variable called grocery_list by adding cookies and double_batch.

In [37]:
#type your code here
grocery_list = np.add(double_batch, Cookies)
print("Grocery List")
grocery_list

Grocery List


array([6.75, 3.  , 5.  , 2.  , 2.  ])